---
title: "Regresion Multiple"
author: "Jared Salinas"
date: "22/1/2019"
output: html_document
---

## Leyendo los datos

```{r}
insurance<-read.csv("Data/insurance.csv",stringsAsFactors = TRUE)
```


## Obteniendo la información de los datos

```{r}
str(insurance)
summary(insurance)
summary(insurance$charges)#charges equals expenses
hist(insurance$charges)
```

## Ver correlación
```{r}
colnames(insurance)
cor(insurance[c("age","bmi","children","charges")])
```

## Viendo gráfica
```{r}
pairs(insurance[c("age","bmi","children","charges")])
#aumented our dataset
install.packages("psych",repos = "http://cran.us.r-project.org")
library(psych)
pairs.panels(insurance[c("age","bmi","children","charges")])
```

## Crear el modelo de regresion multiple
```{r}
ins_model<-lm(charges~age+children+bmi+sex+smoker+region,data=insurance)
ins_model
summary(ins_model)
```

## Mejorando el modelo

```{r}
insurance$age2<-insurance$age^2
insurance$bmi30<-ifelse(insurance$bmi>=30,1,0)

ins_model2<-lm(charges~age+age2+children+bmi+sex+bmi30*smoker+region,data=insurance)

summary(ins_model2)
```

